name: $(GitVersion.AssemblySemVer)
trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - Src/Contractr.Api/**
  
pool:
  vmImage: "ubuntu-latest"
variables:
  dotnetVersion: '8.x'
  projects: '*.csproj'
  artifactName: 'Contractr.Web'
  serviceConnection: DWTECH
  workingdir: '$(Build.SourcesDirectory)/Src/Contractr.Api'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps: 
          - checkout: self
            persistCredentials: true
            fetchDepth: 0

          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: '5.x'
              
          - task: gitversion/execute@0
            displayName: Determine Version Number
            inputs:
              configFilePath: $(workingdir)/GitVersion.yml

          - task: DotNetCoreCLI@2
            displayName: Restore Packages
            inputs:
              command: 'restore'
              projects: '$(workingdir)/*.csproj'
              noCache: true
              verbosityRestore: 'quiet'

          - task: DotNetCoreCLI@2
            displayName: Build Project
            inputs:
              command: 'build'
              projects: '$(workingdir)/*.csproj'
              arguments: >
                --configuration Release
                --no-restore
                -p:FileVersion=$(GitVersion.AssemblySemVer)
                -p:InformationalVersion=$(GitVersion.AssemblySemVer)
                
          - task: DotNetCoreCLI@2
            displayName: Dotnet Publish      
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
            inputs:
              command: publish
              projects: '$(workingdir)/*.csproj'
              publishWebProjects: false
              zipAfterPublish: true
              arguments: >
                --configuration Release
                --no-restore
                --output $(Build.ArtifactStagingDirectory)
                -p:FileVersion=$(GitVersion.AssemblySemVer)
                -p:InformationalVersion=$(GitVersion.AssemblySemVer)

          - task: PublishPipelineArtifact@0
            displayName: Publish Pipeline Artifact
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) 
            inputs:
              artifactName: '$(artifactName)'
              targetPath: '$(Build.ArtifactStagingDirectory)'
          
          - task: Bash@3
            displayName: 'Create Git Tag'
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              targetType: 'inline'
              script: |
                git config --global user.email "azure-pipeline@example.com"
                git config --global user.name "Azure Pipeline"
                git tag -a "v$(GitVersion.AssemblySemVer)" -m "[skip ci] Release v$(GitVersion.AssemblySemVer)"
                git push origin "v$(GitVersion.AssemblySemVer)"

  - stage: Deploy_Dev
    displayName: Deploy To Dev
    dependsOn:
      - Build
    jobs:
    - job: Dev
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifactName: '$(artifactName)'
            targetPath: $(Build.SourcesDirectory)/bin
            
        - task: AzureWebApp@1
          displayName: Publish To App Service
          inputs:
            azureSubscription: $(serviceConnection)
            appType: 'webApp'
            appName: ctr-as-ctrapi-use2-dev
            package: '$(Build.SourcesDirectory)/bin/**/*.zip'
      


