window._env_ = {
  GENERATE_SOURCEMAP: "false",
  API_URL: "#{API_URL}#",
  NOTIFICATION_API_URL: "#{NOTIFICATION_API_URL}#",
  AUTH0_CLIENT_ID: "#{AUTH0_CLIENT_ID}#",
  AUTH0_DOMAIN: "#{AUTH0_DOMAIN}#",
  AUTH0_AUDIENCE: "#{AUTH0_AUDIENCE}#",
} 