trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - Src/Contractr.Database/**

variables:
  flyWayVersion: '8.0.0'
  serviceConnection: DWTECH

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
        - checkout: self
          persistCredentials: true
          fetchDepth: 0

        - task: gitversion/setup@0
          displayName: Install GitVersion
          inputs:
            versionSpec: '5.x'
        - template: devops_templates/build/flyway.tmpl.yaml
          parameters:
            flyWayVersion: $(flyWayVersion)
        
        # - template: devops_templates/build/flyway_test_mssql.tmpl.yaml
        #   parameters:
        #     flyWayVersion: $(flyWayVersion)
        #     migrationsDirectory: 'Migrations'
        - task: Bash@3
          displayName: 'Create Git Tag'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
          inputs:
            targetType: 'inline'
            script: |
              git config --global user.email "azure-pipeline@example.com"
              git config --global user.name "Azure Pipeline"
              git tag -a "v$(GitVersion.AssemblySemVer)" -m "[skip ci] Release v$(GitVersion.AssemblySemVer)"
              git push origin "v$(GitVersion.AssemblySemVer)"

  - template: devops_templates/deploy/flyway_migrate.tmpl.yaml
    parameters:
      branchFilter: 'refs/heads/master'
      env: Dev
      flyWayVersion: $(flyWayVersion)
      keyVaultName: 'ctr-kvctr-use2-dev'
      migrationsDirectory: 'Migrations'
      previousStage: Build
      serviceConnection: $(serviceConnection)